version: '3.7'
services:
  arangodb_db_container:
    image: arangodb:3.9.1
    restart: unless-stopped
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    volumes:
      - ./arango-data/:/var/lib/arangodb3
      - ./arango-apps/:/var/lib/arangodb3-apps
